apiVersion: v1
kind: Service
metadata:
  name: svc-local-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: nginx-rc-pod
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 80