apiVersion: v1
kind: Service
metadata:
  name: svc-node-port
spec:
  type: NodePort
  selector:
    app: nginx-rc-pod
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
      #If nodePort is not defined, It will work and assign a random port between 30000 and 32767.