#Getting base image ubuntu
FROM ubuntu

MAINTAINER Leomarx Tech Solutions <suporte@leomarx.com>
 # AUTOR
 # Leonardo Marques de Andrade
 # DESCRIÇÃO
 # Docker image for API of Allura Course.
 # VERSÃO 1.0
 # by Leonardo Marques de Andrade 29/01/2022 - Primeira versão do programa.

ADD VERSION .

RUN apt-get update

CMD ["apt-get_upgrade.sh"]

CMD ["echo", "kkkk Hello World!!! from my first docker imagem kkkk"]
