apiVersion: v1
kind: Namespace
metadata:
  name: workshop
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-meta
  namespace: workshop
spec:
  containers:
  - name: nginx-container
    image: nginx